######################################################################
# Automatically generated by qmake (3.0) Wed Oct 14 04:35:43 2015
######################################################################

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

QT += gui core network
QT += widgets

# Input
SOURCES += main.cpp \
			ftpserver.cpp \
    ftpdialog.cpp

HEADERS += \
	ftpserver.h\
    ftpdialog.h

FORMS += \
    ftpdialog.ui
